# Generated by Django 5.1.1 on 2024-10-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('N_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Education_Level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('PHD', 'PHD')], max_length=50)),
                ('Phone_no', models.IntegerField(max_length=12)),
                ('School', models.CharField(choices=[('Tandon', 'Tandon'), ('Stern', 'Stern'), ('Tisch', 'Tisch'), ('Gallatin', 'Gallatin')], max_length=50)),
            ],
        ),
    ]
