# Generated by Django 5.1.1 on 2024-10-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_course_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('faculty_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course_Capacity', models.IntegerField()),
                ('phd_course_capacity', models.IntegerField()),
                ('class_day', models.DateField()),
                ('class_time', models.TimeField()),
                ('description', models.CharField(max_length=1000)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Instructor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='userprofile.facultyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('N_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Education_Level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('PHD', 'PHD')], max_length=50)),
                ('Phone_no', models.CharField(max_length=15)),
                ('School', models.CharField(choices=[('Tandon', 'Tandon'), ('Stern', 'Stern'), ('Tisch', 'Tisch'), ('Gallatin', 'Gallatin')], max_length=50)),
                ('is_ta', models.BooleanField(default=False)),
                ('course_enrolled', models.ManyToManyField(related_name='enrolled_students', to='userprofile.courseinfo')),
                ('ta_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tas', to='userprofile.courseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.courseinfo')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.facultyinfo')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.studentinfo')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='facultyinfo',
            name='ta_students',
            field=models.ManyToManyField(related_name='faculty_tas', through='userprofile.TA', to='userprofile.studentinfo'),
        ),
        migrations.DeleteModel(
            name='course_info',
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
